emails:
  adminAddresses:
    - lucy_baciu_2006@yahoo.com
    - wedosoft.contact@gmail.com
    - alex.suciu@wedosoft.eu
    - arpad.sebesi@wedosoft.eu
    - lucian.baciu@wedosoft.eu

spring:
  mvc.favicon.enabled: false
  favicon.enabled: false
  jmx:
    enabled: false
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      org.hibernate.envers.audit_table_suffix: _LOG
      org.hibernate.envers.revision_field_name: AUDIT_REVISION
      org.hibernate.envers.revision_type_field_name: ACTION_TYPE
    show-sql: false
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/wedosoft?useLegacyDatetimeCode=false&serverTimezone=UTC
    connectionTimeout: 600000
    username: root
#    password: y3bWYA7m1HjJ1NfmLyaJ
    passsword:
    maximumPoolSize: 15
    initialize: true
    validation-query: Select 1
    test-while-idle: true
    continue-on-error: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: wedosoft.contact@gmail.com
    password: WeD0Soft_1234
    properties.mail.smtp:
      socketFactory.port: 465
      socketFactory.class: javax.net.ssl.SSLSocketFactory
      socketFactory.fallback: false
      auth: true
      ssl.enable: true
      starttls.enable: true