USE wedosoft;

CREATE TABLE IF NOT EXISTS message ( `id` INT PRIMARY KEY AUTO_INCREMENT, `name` VARCHAR(100) NOT NULL, `email` VARCHAR(100) NOT NULL, `subject` VARCHAR(300) NOT NULL, `message` VARCHAR(3000) NOT NULL, `sent_on` TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

SET time_zone="+00:00"