version: "3.3"
services:
  database:
    image: mysql:8
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: maptycslarchmont
      MYSQL_DATABASE: wedosoft
    ports:
    - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: java-dockerfile
    image: backend:1
    container_name: backend
    expose:
    - "8080"
    depends_on:
    - database
    volumes:
    - ./logs:/external
    command: ["java", "-jar", "server.jar", "-Xms512m", " -Xmx1024m", "> /external/server.log"]

  nginx:
    build:
      context: .
      dockerfile: nginx-dockerfile
    image: nginx:1
    container_name: nginx
    ports:
    - 80:80
    - 443:443
    depends_on:
    - backend
